### ISSUE TITLE
how to make it work with factiva in english?

### ISSUE THREAD

**Issue by randomgambit** [nalimilan/R.TeMiS#1]
Hello and thanks for this great package. 

I am interested in using it to convert a factiva xml into a dataframe. My understanding is that your package only works with factiva in French?! Is there something I could do to make it work correctly?

Thanks!!

**Comment by nalimilan** [comment]
No, it works with any language. See the instructions in `?FactivaSource`, and the [screencast](http://rtemis.hypotheses.org/files/2017/02/Factiva-animated-tutorial.gif) provided there.

**Comment by randomgambit** [comment]
thanks a lot! but can it create a dataframe of news, headlines, fulltext, topics etc? 
i am more interested in processing the raw xml than getting a tm corpus at this point

**Comment by nalimilan** [comment]
Yes, but you'll have to extract the metadata from the tm corpus to a data frame manually. See the tm docs about this, it has nothing to do with this package.
