### ISSUE TITLE
SnowballC::wordStem and NA

### ISSUE THREAD

**Issue by mmuurr** [nalimilan/R.TeMiS#3]
When `SnowballC::wordStem` is passed `NA` values, it will convert the `NA` to a string, then stem, resulting in something like this:
```R
SnowballC::wordStem(c("foo", NA_character_, "bar"))
[1] "foo" "NA"  "bar"
```
Perhaps `NA` values should remain `NA` in the output, like so?:
```R
SnowballC::wordStem(c("foo", NA_character_, "bar"))
[1] "foo" NA "bar"
```

**Comment by nalimilan** [comment]
Good catch. I've pushed a fix, a new version should be available on CRAN soon.
